Fargowilta/FargowiltasSouls

Buffs/Masomode/Infested.cs
NPCs/FargoGlobalNPC.cs

also i made all the debuff times on npc hit random don't worry about it

globalnpc switches

---

NPCs/FargoGlobalNPC.cs

1000 -> 500hp/sec
body does spiky balls (not head)
head shoots lasers
cultist spawns ancient visions haHAAA
phantasm dragon segments are invincible, only head can be damaged

nerfed golem, buffed cultist

---

NPCs/FargoGlobalNPC.cs
Projectiles/FargoGlobalProjectile.cs
Projectiles/Minions/HallowSword.cs
Projectiles/Minions/SilverSword.cs
Projectiles/Souls/Chlorofuck.cs

-lihzahrds inflict short bloodthirsty on touch, shoot super darts, and when they die they explode super violently into spiky balls
-sand shark family has same bleed enrage mechanic as normal sharks
-bone lee can teleport behind you and give you the nothing personnel kiddo when hit, also obstructed
-slime promotions when left alive for 10 sec
-baby slime -> mother slime
-slimeling -> corrupt slime
-wingless slimer -> flying slimer
-golem is immune to traps (sorry gay anime bois)
-golem meme regen 500/sec for body&head, 9999/sec for fists
-golem head breathes fire and shoots laser spreads in phase 2
-golem body gets extremely triggered and sprays spiky balls when vulnerable (also it has x2 hp)
-phantasmal dragon inflicts very short clipped wings, the head is the only vulnerable part and …

not sure which changes listed are redundant oh well

---

NPCs/FargoGlobalNPC.cs
Projectiles/FargoGlobalProjectile.cs
Projectiles/Masomode/PhantasmalDeathrayWOF.cs
masomode stuff to test again.txt

Merge terry's changes

---

FargoPlayer.cs
Items/Accessories/Enchantments/PalladiumEnchant.cs
NPCs/FargoGlobalNPC.cs
masomode stuff to test again.txt

-moon lord causes monolith effects corresponding to his vulnerability

---

FargoPlayer.cs
Items/Accessories/Masomode/DubiousCircuitry.cs
Items/Accessories/Masomode/FusedLens.cs
Items/Accessories/Masomode/ReinforcedPlating.cs
Items/Accessories/Souls/MasochistSoul.cs
masomode stuff to test again.txt

-buffed fused lens so all attacks inflict cursed flame/ichor
-removed lump of flesh minion cursed flame/ichor
-updated dubious circuitry and soul of maso

-buffed reinforced plating to 10 defense, 10% DR

---

Buffs/LunarCultist.cs
Buffs/Masomode/MutantNibble.cs
Buffs/Masomode/Sadism.cs
Buffs/Minions/Probes.cs
Buffs/Minions/TrueEyes.cs
FargoPlayer.cs
Fargowiltas.cs
Items/Accessories/Enchantments/FrostEnchant.cs
Items/Accessories/Masomode/CyclonicFin.cs
Items/Accessories/Souls/MasochistSoul.cs
NPCs/FargoGlobalNPC.cs
NPCs/RoyalSubject.cs
Projectiles/BossWeapons/DungeonGuardianNecro.cs
Projectiles/FargoGlobalProjectile.cs
Projectiles/Masomode/SlimeBallHostile.cs
Projectiles/Minions/LunarCultist.cs
Projectiles/Minions/TrueEyeL.cs
Projectiles/Minions/TrueEyeR.cs
Projectiles/Minions/TrueEyeS.cs
Projectiles/SpectralFishron.cs
masomode stuff to test again.txt

-ML socket lasers actually stop when ML dies
-vortex pillar fires cultist lightning orb and periodically reflects projectiles
-stardust pillar emits omnidirectional rings of ancient light, 8sec
-solar pillar shoots 6-spreads of cultist's homing fireballs
-nebula pillar continuously shoots bolts that rain down on you and FUCKING TELEPORTS
-srollers no longer have boosted defense, only have 200% max life
-maso minions no longer spawn targeting npc at index 0
-maso minions are better about forgetting distant targets
-pillars have 500% life, works in MP(?)
-nerfed hornet/suckler fake death rate

pillar buffs n stuff

---

NPCs/FargoGlobalNPC.cs
masomode stuff to test again.txt

-sand shark specifically spawn in UNDERGROUND desert

---

FargoPlayer.cs
Items/Ammos/FargoArrow.cs
Items/Ammos/FargoBullet.cs
NPCs/FargoGlobalNPC.cs
masomode stuff to test again.txt

-updated shadowflame aura enchant visual
-increased sadisms needed for amalg ammo recipes

-wither beasts have reverse aura now

---

NPCs/FargoSoulsGlobalNPC.cs
Projectiles/Masomode/BetsyDash.cs
masomode stuff to test again.txt

evil bunnies drop calming too
fixed hallow mimic not dropping pots
blue/pink/green jellies drop pots
giant bats drop sonar pot (replacing ice bat)
fixed yellow slimes not dropping recall
tried something to prevent betsy dash wallclipping

stuff, stuff

---

FargoPlayer.cs
Items/Weapons/SwarmDrops/HellZone.cs
NPCs/FargoSoulsGlobalNPC.cs
NPCs/MutantBoss/MutantBoss.cs
masomode stuff to test again.txt

revives shouldnt be memed by mutant fang anymore
hellzone has 66% chance to not consume ammo

mutant shouldnt bump you from eyes to bomb anymore

---

NPCs/AbomBoss/AbomBoss.cs
NPCs/FargoSoulsGlobalNPC.cs
masomode stuff to test again.txt

adjusted abom despawn during sword attacks

fixed eow scaling per segment killed!!!!

---

Items/Accessories/Souls/ColossusSoul.cs

you're welcome fargo :echcrisp:

added anhk shield back in for you

---

NPCs/FargoSoulsGlobalNPC.cs
NPCs/MutantBoss/MutantBoss.cs
Projectiles/FargoGlobalProjectile.cs
Projectiles/MutantBoss/MutantGiantDeathray2.cs
masomode stuff to test again.txt

hallow stars exempt from cooldown (just holy arrows now)

removed prime's hallow star resist

---

Projectiles/BossWeapons/HiveSentry.cs

literally a one line change buffed this item so much lol

better hive wand

---

Fargowiltas.cs

Force of the Desolation to Force of Desolation
Force of the Devastation to Force of Devastation
Force of the Apocalypse to Force of Annihilation

fix soul toggle typos + update calam force names

---

Items/Accessories/Enchantments/MonkEnchant.cs
Items/Accessories/Enchantments/PumpkinEnchant.cs

Fixed some typos

---

Items/Misc/TopHatSquirrelCaught.cs
Items/Misc/TophatSquirrelCaught.cs
Items/Weapons/Misc/TophatSquirrelWeapon.cs

make top hat squirrel critter item names match the other squirrel things

---

.gitignore
Properties/launchSettings.json
UI/UIDragablePanel.cs

Debugging is now possible, and cleaned up some ui. I might've accidentally fixed the draggingbug

Cleaned up UI and added launchSettings

---

Buffs/Boss/MutantPresence.cs

Update Chinese Translation

---

UI/UIDragablePanel.cs

Dragging no longer happens out of scrolling.
Ech.

Dragging now works for the memers

---

Localization/zh-Hans.hjson

began localisation

---

FargowiltasSoulsModCompatibility.cs

boss checklist got updated, making moon lord display as the final boss. this is an updated value list that makes the bosses align better

better boss checklist

---

Items/Accessories/Forces/SpiritForce.cs

actually the most minor typo fix in the entire world

---

EModePlayer.cs
Items/EModeGlobalItem.cs
Items/Summons/CoffinSummon.cs
Items/Weapons/Challengers/SpiritLongbow.cs
NPCs/Challengers/CursedCoffin.cs
Projectiles/EModeGlobalProjectile.cs

unfinished things marked with //TODO JAVYZ

disabled everything unfinished to my knowledge

---

NPCs/Challengers/LifeChallenger.cs

Fixed lieflight despawning immediately in multiplayer

Multiplayer despawn issue fix

---

Items/Weapons/Challengers/CrystallineCongregation.cs
Items/Weapons/Challengers/EnchantedLifeblade.cs
Items/Weapons/Challengers/KamikazePixieStaff.cs
Items/Weapons/Challengers/Lightslinger.cs
NPCs/Challengers/LifeChallenger.cs

At time of writing, contains:
-Lieflight weapon balance changes
-Lieflight mp hotfix

Changes for next patch

---

Content/Bosses/VanillaEternity/Golem.cs
Content/Bosses/VanillaEternity/LunaticCultist.cs
Content/Items/Accessories/Enchantments/ObsidianEnchant.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Nebula/LunarTowerNebula.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Nebula/NebulaPillarProj.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Nebula/PillarArcanum.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Solar/LunarTowerSolar.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Solar/SolarFlamePillar.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Solar/SolarMeteor.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Stardust/LunarTowerStardust.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Stardust/StardustMinion.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Vortex/LunarTowerVortex.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Vortex/VortexVortex.cs
Content/NPCs/EternityModeNPCs/VanillaEnemies/LunarEvents/Vortex/VortexVortexProjectile.cs
Content/Projectiles/FargoSoulsGlobalProjectile.cs
Content/Tiles/MutantStatueGift.cs
Core/ModPlayers/FargoSoulsPlayer.cs
Core/ModPlayers/HitEffectsPlayer.cs
Localization/en-US.hjson
Localization/es-ES.hjson
Localization/pt-BR.hjson
Localization/zh-Hans.hjson

Compensation nerfs against 1.4.4 buffs to make their health equal to pre-1.4.4 Eternity Mode

Compensation nerfs for Lunatic Cultist and Golem

---

Content/Items/Accessories/Enchantments/PumpkinEnchant.cs
Content/Projectiles/Souls/GrowingPumpkin.cs
Localization/en-US.hjson
Localization/es-ES.hjson
Localization/pt-BR.hjson
Localization/zh-Hans.hjson

Pumpkin spawntime 5s>7.5s
Pumpkin flame damage 30>15
Wiz pumpkin flame damage 30>45

pumpkin ench nerfs

---

Core/ModPlayers/UpdatesPlayer.cs
Localization/en-US.hjson
Localization/es-ES.hjson
Localization/pt-BR.hjson
Localization/zh-Hans.hjson

buffed healing from 120%>140%
buffed wiz effect from 140%>170%

hallowed enchant buff

---

Content/Buffs/Souls/MonkBuff.cs
Content/Items/Accessories/Enchantments/ChlorophyteEnchant.cs
Content/Items/Accessories/Enchantments/JungleEnchant.cs
Content/Items/Accessories/Enchantments/MeteorEnchant.cs
Content/Items/Accessories/Enchantments/MonkEnchant.cs
Content/Items/Accessories/Enchantments/ShinobiEnchant.cs
Content/Items/Accessories/Enchantments/TungstenEnchant.cs
Content/Items/Accessories/Forces/ShadowForce.cs
Content/Projectiles/Souls/CopperLightning.cs
Content/Projectiles/Souls/MeteorFlame.cs
Content/Projectiles/Souls/MonkDashDamage.cs
Core/ModPlayers/AccessoryEffectsPlayer.cs
Core/ModPlayers/AccessoryFieldsPlayer.cs
Core/ModPlayers/FargoSoulsPlayer.cs
Core/Systems/CustomDashManager.cs
Localization/en-US.hjson
Localization/es-ES.hjson
Localization/pt-BR.hjson
Localization/zh-Hans.hjson

…messy >:(
fixed Not Healing
dashing through enemies with monk enchant now deals 500 damage, 1000 with wizard
removed all the annoying "tooltip not used" warnings :/
copper lightning nerf uses the system thats??? already there??? guh????????

Monk enchant buff (wip) + a bunch of other random shit to make code less ugly

---

Content/Buffs/Souls/MonkBuff.cs
Content/Items/Accessories/Enchantments/AncientHallowEnchant.cs
Content/Items/Accessories/Enchantments/FrostEnchant.cs
Content/Items/Accessories/Enchantments/HallowEnchant.cs
Content/Items/Accessories/Enchantments/NinjaEnchant.cs
Content/Items/Accessories/Enchantments/ShinobiEnchant.cs
Content/Items/Accessories/Enchantments/TungstenEnchant.cs
Content/Items/Accessories/Forces/ShadowForce.cs
Content/Projectiles/Souls/MonkDashDamage.cs
Core/ModPlayers/AccessoryEffectsPlayer.cs
Core/ModPlayers/AccessoryFieldsPlayer.cs
Localization/en-US.hjson
Localization/es-ES.hjson
Localization/pt-BR.hjson
Localization/zh-Hans.hjson

tungsten 
no speed penalty
7% extra damage, 14 in force
ahallowed, hallowed, ninja, frost recipe changes

misc cleanup + tungsten changes + recipe changes

---

Content/Items/Accessories/Enchantments/TungstenEnchant.cs
Content/Projectiles/BossWeapons/EyeProjectile.cs
Content/Projectiles/BossWeapons/MechEyeProjectile.cs
Content/Projectiles/BossWeapons/MechFlail.cs
Content/Projectiles/BossWeapons/PhantasmalFlail.cs
Content/Projectiles/BossWeapons/ReleasedMechFlail.cs
Localization/en-US/Mods.FargowiltasSouls.Items.hjson
Localization/es-ES/Mods.FargowiltasSouls.Items.hjson
Localization/pt-BR/Mods.FargowiltasSouls.Items.hjson

greatly improved eyeleash eye projectile idle behaviors 
made released mech flail immune to tungsten enchant
greatly improved released mech flail behavior

finished eyeleash and mech flail reworks

---

Content/Projectiles/BossWeapons/EyeProjectile.cs
Content/Projectiles/BossWeapons/MechEyeProjectile.cs
Content/Projectiles/BossWeapons/ReleasedMechFlail.cs
Content/Projectiles/BossWeapons/RetiDeathray.cs
Content/Projectiles/BossWeapons/Retiglaive.cs
Content/Projectiles/BossWeapons/Spazmaglaive.cs
Content/Projectiles/BossWeapons/Spazmarang.cs
Localization/en-US/Mods.FargowiltasSouls.Items.hjson
Localization/es-ES/Mods.FargowiltasSouls.Items.hjson
Localization/pt-BR/Mods.FargowiltasSouls.Items.hjson
Localization/ru-RU/Mods.FargowiltasSouls.Items.hjson

fixed gemini glaive laser's doing magic damage
fixed? iframe issues with gemini glaive right click functions 
removed twinrang explosion synergy
mechleash no longer spawns servants on hit
mechleash servants pierce once and have local iframes now 
made it so the detatched leash of cthulhu despawns after 2 seconds if it cant find/loses sight of its target

fixed eyeleash tooltip having asterisks

---

Content/Items/Weapons/BossDrops/BoneZone.cs
Content/Projectiles/BossWeapons/EyeProjectile.cs

fixed bonezone clothier curse iframes

gave eyeleash eye projectiles afterimages when launched.

---

Localization/en-US/Mods.FargowiltasSouls.Items.hjson
Localization/es-ES/Mods.FargowiltasSouls.Items.hjson
Localization/pt-BR/Mods.FargowiltasSouls.Items.hjson
Localization/zh-Hans/Mods.FargowiltasSouls.Items.hjson

- Added Accessory Icons of relevant effects to Angler, Bee and Rain Enchantments
- Slightly reworded Meteor Enchantment

- Tooltip tweaks to Various Enchantments

---

Content/Items/Weapons/BossDrops/LeashOfCthulhu.cs
Content/Items/Weapons/Challengers/SisypheanFist.cs
Content/Projectiles/BossWeapons/LeashFlail.cs
Content/Projectiles/ChallengerItems/SandstoneBoulder.cs
Localization/es-ES/Mods.FargowiltasSouls.Items.hjson
Localization/pt-BR/Mods.FargowiltasSouls.Items.hjson

Eyeleash base damage 14 -> 9, servant base damage 1.6x -> 2x, servant spawn rate 2/s -> 3/s (rename EyeProjectile2 to some servant name later)
Sisyphean Fist base damage 82 -> 70, initial throw base projectile velocity 20f -> 22f

2.0 evils minor balance

---

Content/Items/EModeItemBalance.cs
Content/Projectiles/EModeGlobalProjectile.cs

Ice Blade, Flower Pow, Pygmy Staff, Super Star Shooter, Zenith, Ice Barrier and Hallowed dodge

Fixed HasEmodeChange not working, causing several items to not have EMode changes

---

Content/Bosses/VanillaEternity/Destroyer.cs

Gave Probes recoil whenever firing a laser.

Probe glowmasks fade away when falling.

---

Content/Buffs/TwinsInstallBuff.cs
Content/Items/EModeItemBalance.cs
Content/Projectiles/FargoSoulsGlobalProjectile.cs
Content/Projectiles/Souls/ArrowRain.cs
FargowiltasSoulsDetours.cs

Fixed Twinstall not reducing defense
HasEmodeChange now checks for Eternity mode
Fixed Red Riding Enchantment's Arrow Rain triggering Phantasm's phantom arrows

More fixes

---

Content/PlayerDrawLayers/MutantMaskDrawLayer.cs

Fixed Mutant Mask failing to draw when equipped in vanity slots.
Fixed Mutant Mask skipping a frame when animating.
Fixed weird issue that caused the Mutant Mask sprite to jitter while moving.

Mutant Mask fixes.

---

Content/Items/EModeItemBalance.cs
Content/Projectiles/EModeGlobalProjectile.cs
Content/Projectiles/Weapons/Minions/BigBrainProj.cs
Content/Projectiles/Weapons/Minions/EaterBody.cs
Content/Projectiles/Weapons/Minions/EaterHead.cs
Content/Projectiles/Weapons/Minions/EaterTail.cs

IgnoreMinionNerf, MinionStack nerf, NerfDamageBasedOnProjTypeCount, Archery and Magic Quiver nerfs, and their remnants

Removed redundant code
